# Generated by Django 2.0.4 on 2018-11-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('sogo_app', '0004_auto_20181105_1911'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='user',
        #    name='user_ptr',
        #),
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
