# Generated by Django 2.0.4 on 2018-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sogo_app', '0006_auto_20181105_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
