# Generated by Django 2.0.4 on 2018-11-15 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sogo_app', '0011_auto_20181115_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gritchallenge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
