# Generated by Django 2.0.4 on 2018-11-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sogo_app', '0013_auto_20181116_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='result',
            new_name='duration',
        ),
    ]
