# Generated by Django 2.0.4 on 2018-11-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sogo_app', '0014_auto_20181116_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='reps',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='sets',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
